version: '3.4'
services:
  hybris:
    image: hybris-b2b
    build:
      context: hybris-b2b
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
      - "9002:9002"

  spartacus:
    image: spartacus
    build:
      context: spartacus
      dockerfile: Dockerfile
    environment:
      - OCC_URL=https://host.docker.internal:9002/occ/v2
    ports: 
      - "4200:4200"
    depends_on:
      - hybris